/*
 * Dark control dashboard served from GET / and GET /dashboard.
 *
 * The page itself is public but carries no secrets: every data call is made
 * from the browser with a key the operator pastes in, kept in sessionStorage
 * only. See util.js for the style note (no backticks, no backslash escapes).
 */

import { DEFAULT_IDLE_TIMEOUT_MS, DEFAULT_MACHINE, NL, SERVER_NAME, SERVER_VERSION, clampInt } from "./util.js";

export function dashboardHtml(env) {
  const repo = String(env.REPO_OWNER || "unset") + "/" + String(env.REPO_NAME || "unset");
  const machine = env.CODESPACE_MACHINE || DEFAULT_MACHINE;
  const idleMinutes = Math.round(clampInt(env.IDLE_TIMEOUT_MS, 60000, 86400000, DEFAULT_IDLE_TIMEOUT_MS) / 60000);

  const lines = [];
  lines.push("<!doctype html>");
  lines.push("<html lang='en'>");
  lines.push("<head>");
  lines.push("<meta charset='utf-8' />");
  lines.push("<meta name='viewport' content='width=device-width, initial-scale=1' />");
  lines.push("<title>" + SERVER_NAME + "</title>");
  lines.push("<style>");
  lines.push(":root{--bg:#0b0d12;--panel:#12151d;--panel2:#171b25;--line:#232838;--txt:#e7ebf5;--dim:#8b93a7;--acc:#7c5cff;--ok:#3ddc97;--warn:#ffc857;--err:#ff6b6b;--mono:ui-monospace,SFMono-Regular,Menlo,Consolas,monospace}");
  lines.push("*{box-sizing:border-box}");
  lines.push("body{margin:0;background:var(--bg);color:var(--txt);font:14px/1.5 -apple-system,BlinkMacSystemFont,'Segoe UI',Inter,Roboto,sans-serif}");
  lines.push("body:before{content:'';position:fixed;inset:0;pointer-events:none;background:radial-gradient(1100px 460px at 78% -12%,rgba(124,92,255,.20),transparent 62%),radial-gradient(760px 380px at 6% 0%,rgba(61,220,151,.09),transparent 60%)}");
  lines.push(".wrap{position:relative;max-width:1080px;margin:0 auto;padding:34px 22px 70px}");
  lines.push("header{display:flex;flex-wrap:wrap;gap:14px;align-items:baseline;justify-content:space-between;margin-bottom:22px}");
  lines.push("h1{margin:0;font-size:21px;letter-spacing:.2px}");
  lines.push("h1 span{color:var(--acc)}");
  lines.push(".sub{color:var(--dim);font-size:12.5px;font-family:var(--mono)}");
  lines.push(".card{background:linear-gradient(180deg,var(--panel),var(--panel2));border:1px solid var(--line);border-radius:14px;padding:16px 18px}");
  lines.push(".keybar{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-bottom:18px}");
  lines.push("input,textarea,button{font-family:inherit;font-size:13.5px;color:var(--txt);background:#0e1118;border:1px solid var(--line);border-radius:10px;padding:10px 12px;outline:none}");
  lines.push("input:focus,textarea:focus{border-color:var(--acc);box-shadow:0 0 0 3px rgba(124,92,255,.16)}");
  lines.push("input{flex:1;min-width:240px;font-family:var(--mono)}");
  lines.push("textarea{width:100%;min-height:76px;resize:vertical;font-family:var(--mono)}");
  lines.push("button{cursor:pointer;background:var(--acc);border-color:transparent;color:#fff;font-weight:600;padding:10px 16px;transition:.15s}");
  lines.push("button:hover{filter:brightness(1.12)}");
  lines.push("button.ghost{background:#0e1118;color:var(--txt);border-color:var(--line);font-weight:500}");
  lines.push("button.danger{background:transparent;border-color:rgba(255,107,107,.45);color:var(--err)}");
  lines.push(".grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(212px,1fr));gap:14px;margin-bottom:18px}");
  lines.push(".k{color:var(--dim);font-size:11px;text-transform:uppercase;letter-spacing:.9px;margin-bottom:7px}");
  lines.push(".v{font-size:19px;font-weight:650;font-family:var(--mono);word-break:break-all}");
  lines.push(".v small{display:block;font-size:11.5px;font-weight:400;color:var(--dim);margin-top:5px;font-family:var(--mono)}");
  lines.push(".dot{display:inline-block;width:8px;height:8px;border-radius:50%;margin-right:7px;vertical-align:1px}");
  lines.push(".ok{color:var(--ok)}.warn{color:var(--warn)}.err{color:var(--err)}.dim{color:var(--dim)}");
  lines.push(".bg-ok{background:var(--ok)}.bg-warn{background:var(--warn)}.bg-err{background:var(--err)}.bg-dim{background:var(--dim)}");
  lines.push("section{margin-bottom:18px}");
  lines.push("h2{font-size:12px;text-transform:uppercase;letter-spacing:1px;color:var(--dim);margin:0 0 10px}");
  lines.push(".row{display:flex;gap:10px;flex-wrap:wrap;align-items:center;margin-top:10px}");
  lines.push("pre{margin:12px 0 0;padding:13px;background:#080a0f;border:1px solid var(--line);border-radius:10px;font-family:var(--mono);font-size:12.5px;white-space:pre-wrap;word-break:break-word;max-height:340px;overflow:auto}");
  lines.push("table{width:100%;border-collapse:collapse;font-size:12.5px}");
  lines.push("th{text-align:left;color:var(--dim);font-weight:500;font-size:11px;text-transform:uppercase;letter-spacing:.7px;padding:0 10px 9px 0;border-bottom:1px solid var(--line)}");
  lines.push("td{padding:9px 10px 9px 0;border-bottom:1px solid rgba(35,40,56,.55);vertical-align:top;font-family:var(--mono)}");
  lines.push("td.cmd{font-family:var(--mono);color:var(--txt);word-break:break-all}");
  lines.push("tr.clickable{cursor:pointer}tr.clickable:hover td{background:rgba(124,92,255,.07)}");
  lines.push(".log{font-family:var(--mono);font-size:12px;max-height:240px;overflow:auto}");
  lines.push(".log div{padding:4px 0;border-bottom:1px solid rgba(35,40,56,.45);color:var(--dim)}");
  lines.push(".log b{color:var(--txt);font-weight:600}");
  lines.push(".note{color:var(--dim);font-size:12px;margin-top:9px;font-family:var(--mono)}");
  lines.push("</style>");
  lines.push("</head>");
  lines.push("<body><div class='wrap'>");
  lines.push("<header>");
  lines.push("<div><h1>codespace <span>mcp</span> gateway</h1>");
  lines.push("<div class='sub'>" + repo + " &middot; " + machine + " &middot; idle teardown " + idleMinutes + " min &middot; v" + SERVER_VERSION + "</div></div>");
  lines.push("<div class='sub' id='clock'>&nbsp;</div>");
  lines.push("</header>");
  lines.push("<div class='keybar card'>");
  lines.push("<input id='key' type='password' placeholder='gateway API key (x-api-key)' autocomplete='off' spellcheck='false' />");
  lines.push("<button id='connect'>Connect</button>");
  lines.push("<button class='ghost' id='refresh'>Refresh</button>");
  lines.push("</div>");
  lines.push("<div class='grid'>");
  lines.push("<div class='card'><div class='k'>codespace</div><div class='v' id='cs'>&mdash;</div></div>");
  lines.push("<div class='card'><div class='k'>queue</div><div class='v' id='queue'>&mdash;</div></div>");
  lines.push("<div class='card'><div class='k'>in-codespace agent</div><div class='v' id='agent'>&mdash;</div></div>");
  lines.push("<div class='card'><div class='k'>auto teardown</div><div class='v' id='teardown'>&mdash;</div></div>");
  lines.push("</div>");
  lines.push("<section class='card'>");
  lines.push("<h2>run a command</h2>");
  lines.push("<textarea id='cmd' placeholder='uname -a &amp;&amp; node --version &amp;&amp; pwd' spellcheck='false'></textarea>");
  lines.push("<div class='row'>");
  lines.push("<button id='run'>Run</button>");
  lines.push("<button class='ghost' id='keepalive'>Keep alive 15 min</button>");
  lines.push("<button class='ghost' id='start'>Start codespace</button>");
  lines.push("<button class='danger' id='stop'>Tear down now</button>");
  lines.push("</div>");
  lines.push("<pre id='out'>Paste the gateway key above and press Connect.</pre>");
  lines.push("</section>");
  lines.push("<section class='card'>");
  lines.push("<h2>commands</h2>");
  lines.push("<table><thead><tr><th>when</th><th>status</th><th>exit</th><th>took</th><th>command</th></tr></thead><tbody id='rows'></tbody></table>");
  lines.push("<div class='note' id='rowsnote'>&nbsp;</div>");
  lines.push("</section>");
  lines.push("<section class='card'>");
  lines.push("<h2>lifecycle log</h2>");
  lines.push("<div class='log' id='log'></div>");
  lines.push("</section>");
  lines.push("</div>");
  lines.push("<script>");
  lines.push('var STORE = "codespace-mcp-key";');
  lines.push('var key = sessionStorage.getItem(STORE) || "";');
  lines.push("var busy = false;");
  lines.push("var lastState = null;");
  lines.push("function el(id) { return document.getElementById(id); }");
  lines.push('function esc(v) { return String(v === null || v === undefined ? "" : v).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;"); }');
  lines.push("function head() { return { 'content-type': 'application/json', 'x-api-key': key }; }");
  lines.push("function secs(ms) { return Math.max(0, Math.round(ms / 1000)); }");
  lines.push("function ago(ts) {");
  lines.push('  if (!ts) return "never";');
  lines.push('  return secs(Date.now() - ts) + " s ago";');
  lines.push("}");
  lines.push("function clock() {");
  lines.push('  el("clock").textContent = new Date().toISOString().replace("T", " ").slice(0, 19) + " UTC";');
  lines.push("}");
  lines.push("function dot(cls) {");
  lines.push('  return "<span class=\'dot bg-" + cls + "\'></span>";');
  lines.push("}");
  lines.push("function render(st) {");
  lines.push("  lastState = st;");
  lines.push("  var cs = st.codespace;");
  lines.push("  if (cs) {");
  lines.push('    var cls = cs.stateClass === "ready" ? "ok" : (cs.stateClass === "stopped" ? "warn" : (cs.stateClass === "dead" ? "err" : "warn"));');
  lines.push('    el("cs").innerHTML = dot(cls) + esc(cs.state) + "<small>" + esc(cs.name) + "</small><small>" + esc(cs.machine || st.machine) + (cs.cores ? " / " + cs.cores + " cores" : "") + (cs.createdByGateway ? " / created by gateway" : " / reused") + "</small>";');
  lines.push("  } else {");
  lines.push('    el("cs").innerHTML = dot("dim") + "none<small>next command creates one</small><small>" + esc(st.machine) + "</small>";');
  lines.push("  }");
  lines.push('  el("queue").innerHTML = st.counts.running + " running<small>" + st.counts.queued + " queued / " + st.counts.total + " tracked</small>";');
  lines.push('  el("agent").innerHTML = dot(st.agent.online ? "ok" : "dim") + (st.agent.online ? "online" : "offline") + "<small>seen " + ago(st.agent.lastSeenAt) + "</small>";');
  lines.push("  if (st.teardownAt === null) {");
  lines.push('    el("teardown").innerHTML = dot("ok") + "held<small>work in flight</small>";');
  lines.push("  } else if (!cs) {");
  lines.push('    el("teardown").innerHTML = dot("dim") + "idle<small>nothing running</small>";');
  lines.push("  } else {");
  lines.push('    el("teardown").innerHTML = dot("warn") + secs(st.teardownInMs) + " s<small>" + new Date(st.teardownAt).toISOString().slice(11, 19) + " UTC</small>";');
  lines.push("  }");
  lines.push('  var out = "";');
  lines.push("  var cmds = st.commands || [];");
  lines.push("  for (var i = 0; i < cmds.length; i++) {");
  lines.push("    var c = cmds[i];");
  lines.push('    var scls = c.status === "done" ? (c.exitCode === 0 ? "ok" : "warn") : (c.status === "error" ? "err" : (c.status === "running" ? "warn" : "dim"));');
  lines.push('    out += "<tr class=clickable data-id=" + c.id + ">";');
  lines.push('    out += "<td class=dim>" + new Date(c.createdAt).toISOString().slice(11, 19) + "</td>";');
  lines.push('    out += "<td class=" + scls + ">" + dot(scls) + esc(c.status) + "</td>";');
  lines.push('    out += "<td>" + (c.exitCode === null ? "-" : c.exitCode) + "</td>";');
  lines.push('    out += "<td class=dim>" + (c.durationMs === null ? "-" : (c.durationMs / 1000).toFixed(1) + " s") + "</td>";');
  lines.push('    out += "<td class=cmd>" + esc(c.command) + "</td></tr>";');
  lines.push("  }");
  lines.push('  el("rows").innerHTML = out || "<tr><td colspan=5 class=dim>no commands yet</td></tr>";');
  lines.push('  el("rowsnote").textContent = cmds.length ? "click a row to load its full output" : " ";');
  lines.push('  var log = "";');
  lines.push("  var evs = st.events || [];");
  lines.push("  for (var j = 0; j < evs.length; j++) {");
  lines.push("    var e = evs[j];");
  lines.push('    var extra = e.detail ? " " + esc(JSON.stringify(e.detail)) : "";');
  lines.push('    log += "<div>" + new Date(e.at).toISOString().slice(11, 19) + " <b>" + esc(e.type) + "</b>" + extra + "</div>";');
  lines.push("  }");
  lines.push('  el("log").innerHTML = log || "<div>no events yet</div>";');
  lines.push("}");
  lines.push("function show(text) {");
  lines.push('  el("out").textContent = text;');
  lines.push("}");
  lines.push("async function call(path, options) {");
  lines.push("  var init = options || {};");
  lines.push("  init.headers = head();");
  lines.push('  init.cache = "no-store";');
  lines.push("  var res = await fetch(path, init);");
  lines.push("  var text = await res.text();");
  lines.push("  var data = null;");
  lines.push("  try { data = JSON.parse(text); } catch (err) { data = { raw: text }; }");
  lines.push("  if (!res.ok) {");
  lines.push('    var msg = data && data.message ? data.message : (data && data.error ? data.error : "HTTP " + res.status);');
  lines.push('    throw new Error(res.status + ": " + msg);');
  lines.push("  }");
  lines.push("  return data;");
  lines.push("}");
  lines.push("async function refresh() {");
  lines.push("  if (!key) return;");
  lines.push("  try {");
  lines.push('    var st = await call("/api/state");');
  lines.push("    render(st);");
  lines.push("  } catch (err) {");
  lines.push('    show("state error: " + err.message);');
  lines.push("  }");
  lines.push("}");
  lines.push("async function run() {");
  lines.push('  var command = el("cmd").value.trim();');
  lines.push('  if (!command) { show("type a command first"); return; }');
  lines.push("  if (busy) return;");
  lines.push("  busy = true;");
  lines.push('  show("queued, waiting for the codespace ...");');
  lines.push("  try {");
  lines.push('    var data = await call("/api/run", { method: "POST", body: JSON.stringify({ command: command, wait_ms: 45000 }) });');
  lines.push("    var c = data.command;");
  lines.push('    var head2 = c.status + (c.exitCode === null ? "" : " (exit " + c.exitCode + ")") + "  " + c.id;');
  lines.push('    var body = (data.stdout || "") + (data.stderr ? "\\n--- stderr ---\\n" + data.stderr : "");');
  lines.push('    show(head2 + "\\n\\n" + (body || "(no output)") + (data.ensureError ? "\\n\\ncodespace warning: " + data.ensureError : ""));');
  lines.push("    if (data.state) render(data.state);");
  lines.push("  } catch (err) {");
  lines.push('    show("run failed: " + err.message);');
  lines.push("  }");
  lines.push("  busy = false;");
  lines.push("}");
  lines.push("async function loadCommand(id) {");
  lines.push("  try {");
  lines.push('    var data = await call("/api/command?id=" + encodeURIComponent(id));');
  lines.push("    var c = data.command;");
  lines.push('    var head3 = c.command + "\\n" + c.status + (c.exitCode === null ? "" : " (exit " + c.exitCode + ")") + "  " + c.id;');
  lines.push('    show(head3 + "\\n\\n" + ((data.stdout || "") + (data.stderr ? "\\n--- stderr ---\\n" + data.stderr : "") || "(no output)"));');
  lines.push("  } catch (err) {");
  lines.push('    show("load failed: " + err.message);');
  lines.push("  }");
  lines.push("}");
  lines.push("async function post(path, body, label) {");
  lines.push("  try {");
  lines.push('    var data = await call(path, { method: "POST", body: JSON.stringify(body || {}) });');
  lines.push('    show(label + ": " + JSON.stringify(data.result || data.ok || data, null, 2).slice(0, 4000));');
  lines.push("    if (data.state) render(data.state);");
  lines.push("    else refresh();");
  lines.push("  } catch (err) {");
  lines.push('    show(label + " failed: " + err.message);');
  lines.push("  }");
  lines.push("}");
  lines.push('el("connect").onclick = function () {');
  lines.push('  key = el("key").value.trim();');
  lines.push("  sessionStorage.setItem(STORE, key);");
  lines.push('  show(key ? "connected, polling /api/state every 3 s" : "key cleared");');
  lines.push("  refresh();");
  lines.push("};");
  lines.push('el("refresh").onclick = refresh;');
  lines.push('el("run").onclick = run;');
  lines.push('el("keepalive").onclick = function () { post("/api/keepalive", { minutes: 15 }, "keep alive"); };');
  lines.push('el("start").onclick = function () { post("/api/run", { command: "echo gateway warmup && uname -a", wait_ms: 20000 }, "warmup"); };');
  lines.push('el("stop").onclick = function () {');
  lines.push('  if (!confirm("Delete the shared codespace now?")) return;');
  lines.push('  post("/api/teardown", { mode: "delete", force: true }, "teardown");');
  lines.push("};");
  lines.push('el("cmd").addEventListener("keydown", function (ev) {');
  lines.push("  if ((ev.metaKey || ev.ctrlKey) && ev.key === 'Enter') { ev.preventDefault(); run(); }");
  lines.push("});");
  lines.push('el("rows").addEventListener("click", function (ev) {');
  lines.push('  var tr = ev.target.closest("tr");');
  lines.push('  if (tr && tr.dataset && tr.dataset.id) loadCommand(tr.dataset.id);');
  lines.push("});");
  lines.push('if (key) el("key").value = key;');
  lines.push("clock();");
  lines.push("setInterval(clock, 1000);");
  lines.push("setInterval(refresh, 3000);");
  lines.push("refresh();");
  lines.push("</script>");
  lines.push("</body>");
  lines.push("</html>");
  return lines.join(NL);
}
